config/routes.rb
Rails.application.routes.draw do

  namespace(:trust_admin){ resources :offerings }
  root :to => 'welcome#index'

  namespace(:super_admin){
    resources :trust_admins
    resources :trusts
    resources :temples
    resources :deities
    resources :images
  }

  namespace(:trust_admin){
    resources :deities do
      resources :offerings
    end
  }

  get     'super_admin/sign_in'         => "super_admin/sessions#sign_in",         :as => :super_admin_sign_in
  post    'super_admin/create_session'  => "super_admin/sessions#create_session",  :as => :super_admin_create_session
  delete  'super_admin/sign_out'        => "super_admin/sessions#sign_out",        :as => :super_admin_sign_out

  get     'super_admin/home'           => "super_admin/home#index",                :as => :super_admin_home

  get     'trust_admin/sign_in'         => "trust_admin/sessions#sign_in",         :as => :trust_admin_sign_in
  post    'trust_admin/create_session'  => "trust_admin/sessions#create_session",  :as => :trust_admin_create_session
  delete  'trust_admin/sign_out'        => "trust_admin/sessions#sign_out",        :as => :trust_admin_sign_out

  get     'trust_admin/home'           => "trust_admin/home#index",                :as => :trust_admin_home

end

app/controllers/admin/deities_controller.rb
class Admin::DeitiesController < ApplicationController

  #before_filter :require_user
  #authorize_actions_for Item, :actions => {:index => :delete}
  before_filter :set_navs, :parse_pagination_params, :only=>:index

  # GET /deities
  # GET /deities.js
  # GET /deities.json
  def index

    get_collections

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @deities }
      format.js {}
    end
  end

  # GET /deities/1
  # GET /deities/1.js
  # GET /deities/1.json
  def show
    ## Creating the deity object
    @deity = Deity.find(params[:id])

    respond_to do |format|
      format.html { get_collections and render :index }
      format.json { render json: @deity }
      format.js {}
    end
  end

  # GET /deities/new
  # GET /deities/new.json
  def new
    ## Intitializing the deity object
    @deity = Deity.new

    respond_to do |format|
      format.html { get_collections and render :index }
      format.json { render json: @deity }
      format.js {}
    end
  end

  # GET /deities/1/edit
  def edit
    ## Fetching the deity object
    @deity = Deity.find(params[:id])

    respond_to do |format|
      format.html { get_collections and render :index }
      format.json { render json: @deity }
      format.js {}
    end
  end

  # POST /deities
  # POST /deities.js
  # POST /deities.json
  def create
    ## Creating the deity object
    @deity = Deity.new(deity_params)

    ## Validating the data
    @deity.valid?

    respond_to do |format|
      if @deity.errors.blank?

        # Saving the deity object
        @deity.save

        # Setting the flash message
        message = translate("forms.created_successfully", :item => "Deity")
        store_flash_message(message, :success)

        format.html {
          redirect_to admin_deity_url(@deity), notice: message
        }
        format.json { render json: @deity, status: :created, location: @deity }
        format.js {}
      else

        # Setting the flash message
        message = @deity.errors.full_messages.to_sentence
        store_flash_message(message, :alert)

        format.html { render action: "new" }
        format.json { render json: @deity.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # PUT /deities/1
  # PUT /deities/1.js
  # PUT /deities/1.json
  def update
    ## Fetching the deity
    @deity = Deity.find(params[:id])

    ## Updating the @deity object with params
    @deity.assign_attributes(deity_params)

    ## Validating the data
    @deity.valid?

    respond_to do |format|
      if @deity.errors.blank?

        # Saving the deity object
        @deity.save

        # Setting the flash message
        message = translate("forms.updated_successfully", :item => "Deity")
        store_flash_message(message, :success)

        format.html {
          redirect_to admin_deity_url(@deity), notice: message
        }
        format.json { head :no_content }
        format.js {}

      else

        # Setting the flash message
        message = @deity.errors.full_messages.to_sentence
        store_flash_message(message, :alert)

        format.html {
          render action: "edit"
        }
        format.json { render json: @deity.errors, status: :unprocessable_entity }
        format.js {}

      end
    end
  end

  # DELETE /deities/1
  # DELETE /deities/1.js
  # DELETE /deities/1.json
  def destroy
    ## Fetching the deity
    @deity = Deity.find(params[:id])

    respond_to do |format|
      ## Destroying the deity
      @deity.destroy
      @deity = Deity.new

      # Fetch the deities to refresh ths list and details box
      get_collections
      @deity = @deities.first if @deities and @deities.any?

      # Setting the flash message
      message = translate("forms.destroyed_successfully", :item => "Deity")
      store_flash_message(message, :success)

      format.html {
        redirect_to admin_deities_url notice: message
      }
      format.json { head :no_content }
      format.js {}

    end
  end

  private

  def set_navs
    set_nav("Deity")
  end

  def get_collections
    # Fetching the deities
    relation = Deity.where("")
    @filters = {}

    if params[:query]
      @query = params[:query].strip
      relation = relation.search(@query) if !@query.blank?
    end

    @deities = relation.order("created_at desc").page(@current_page).per(@per_page)

    ## Initializing the @deity object so that we can render the show partial
    @deity = @deities.first unless @deity

    return true

  end

  def deity_params
    params.require(:deity).permit(:name, :description, :temple_id, :trust_id)
  end

end

app/controllers/super_admin/base_controller.rb
class SuperAdmin::BaseController < ApplicationController

  before_filter :require_super_admin
  layout 'super_admin'

  protected

  def current_super_admin
    @current_super_admin ||= SuperAdmin.find_by_id(session[:super_admin_id])
  end

  def store_session
    session[:super_admin_id] = @current_super_admin.id
  end

  def require_super_admin
    unless current_super_admin
      @heading = translate("authentication.error")
      @alert = translate("authentication.invalid_token")
      store_flash_message("#{@heading}: #{@alert}", :errors)
      redirect_to super_admin_sign_in_url
    end
  end

  def redirect_url_if_sign_in_fails
    super_admin_sign_in_url
  end

  def redirect_url_after_sign_in
    super_admin_home_url
  end

  def redirect_url_after_sign_out
    super_admin_sign_in_url
  end

  def redirect_if_signed_in
    redirect_to redirect_url_after_sign_in if current_super_admin
  end

  def redirect_unless_signed_in
    redirect_to redirect_url_if_sign_in_fails unless current_super_admin
  end

end

app/controllers/super_admin/deities_controller.rb
class SuperAdmin::DeitiesController < SuperAdmin::BaseController

  before_filter :parse_pagination_params, :only=>:index
  before_filter :set_navs

  # GET /deities
  # GET /deities.js
  # GET /deities.json
  def index

    get_collections

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @deities }
      format.js {}
    end
  end

  # GET /deities/1
  # GET /deities/1.js
  # GET /deities/1.json
  def show
    ## Creating the deity object
    @deity = Deity.find(params[:id])

    respond_to do |format|
      format.html { get_collections and render :index }
      format.json { render json: @deity }
      format.js {}
    end
  end

  # GET /deities/new
  # GET /deities/new.json
  def new
    ## Intitializing the deity object
    @deity = Deity.new

    if params[:temple_id]
      @temple = Temple.find_by_id(params[:temple_id])
      @deity.temple = @temple
    end

    respond_to do |format|
      format.html { get_collections and render :index }
      format.json { render json: @deity }
      format.js {}
    end
  end

  # GET /deities/1/edit
  def edit
    ## Fetching the deity object
    @deity = Deity.find(params[:id])

    respond_to do |format|
      format.html { get_collections and render :index }
      format.json { render json: @deity }
      format.js {}
    end
  end

  # POST /deities
  # POST /deities.js
  # POST /deities.json
  def create
    ## Creating the deity object
    @deity = Deity.new(deity_params)

    if params[:deity] && params[:deity][:temple_id]
      @temple = Temple.find_by_id(params[:deity][:temple_id])
      @deity.temple = @temple
      @deity.trust = @temple.trust
    end

    ## Validating the data
    @deity.valid?

    respond_to do |format|
      if @deity.errors.blank?

        # Saving the deity object
        @deity.save

        # Setting the flash message
        message = translate("forms.created_successfully", :item => "Deity")
        store_flash_message(message, :success)

        format.html {
          redirect_to super_admin_deity_url(@deity), notice: message
        }
        format.json { render json: @deity, status: :created, location: @deity }
        format.js {}
      else

        # Setting the flash message
        message = @deity.errors.full_messages.to_sentence
        store_flash_message(message, :alert)

        format.html { render action: "new" }
        format.json { render json: @deity.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # PUT /deities/1
  # PUT /deities/1.js
  # PUT /deities/1.json
  def update
    ## Fetching the deity
    @deity = Deity.find(params[:id])

    ## Updating the @deity object with params
    @deity.assign_attributes(deity_params)

    ## Validating the data
    @deity.valid?

    respond_to do |format|
      if @deity.errors.blank?

        # Saving the deity object
        @deity.save

        # Setting the flash message
        message = translate("forms.updated_successfully", :item => "Deity")
        store_flash_message(message, :success)

        format.html {
          redirect_to super_admin_deity_url(@deity), notice: message
        }
        format.json { head :no_content }
        format.js {}

      else

        # Setting the flash message
        message = @deity.errors.full_messages.to_sentence
        store_flash_message(message, :alert)

        format.html {
          render action: "edit"
        }
        format.json { render json: @deity.errors, status: :unprocessable_entity }
        format.js {}

      end
    end
  end

  # DELETE /deities/1
  # DELETE /deities/1.js
  # DELETE /deities/1.json
  def destroy
    ## Fetching the deity
    @deity = Deity.find(params[:id])

    respond_to do |format|
      ## Destroying the deity
      @deity.destroy
      @deity = Deity.new

      # Fetch the deities to refresh ths list and details box
      get_collections
      @deity = @deities.first if @deities and @deities.any?

      # Setting the flash message
      message = translate("forms.destroyed_successfully", :item => "Deity")
      store_flash_message(message, :success)

      format.html {
        redirect_to super_admin_deities_url notice: message
      }
      format.json { head :no_content }
      format.js {}

    end
  end

  private

  def set_navs
    set_nav("Manage Deities")
  end

  def get_collections
    # Fetching the deities
    relation = Deity.where("")
    @filters = {}

    if params[:query]
      @query = params[:query].strip
      relation = relation.search(@query) if !@query.blank?
    end

    @deities = relation.order("created_at desc").page(@current_page).per(@per_page)

    ## Initializing the @deity object so that we can render the show partial
    @deity = @deities.first unless @deity

    return true

  end

  def deity_params
    params.require(:deity).permit(:name, :unicode_name, :description, :temple_id, :trust_id)
  end

end

app/controllers/super_admin/home_controller.rb
class SuperAdmin::HomeController < SuperAdmin::BaseController

  before_filter :require_super_admin
  before_filter :set_navs, :only=>:index

  # GET /
  def index
  end

  private

  def set_navs
    set_nav("Home")
  end

end

app/controllers/super_admin/images_controller.rb
class SuperAdmin::ImagesController < SuperAdmin::BaseController

  # GET /super_admin/images/new
  # GET /super_admin/images/new.json

  skip_before_filter :set_navs, :parse_pagination_params

  def new
    ## Intitializing the image object

    image_type = params[:image_type] || "Image::Base"

    @image = image_type.constantize.new

    respond_to do |format|
      format.html { get_collections and render :index }
      format.json { render json: @image }
      format.js {}
    end
  end

  # GET /super_admin/images/1/edit
  # GET /super_admin/images/1/edit.js
  # GET /super_admin/images/1/edit.json

  def edit

    ## Fetching the image object
    image_type = params[:image_type] || "Image::Base"
    @image = image_type.constantize.find(params[:id])

    respond_to do |format|
      format.html { get_collections and render :index }
      format.json { render json: @image }
      format.js {}
    end
  end

  # POST /super_admin/images/
  # POST /super_admin/images.js
  # POST /super_admin/images.json
  def create

    ## Creating the image object
    image_type = params[:image_type] || "Image::Base"

    resource = params[:imageable_type].constantize.find params[:imageable_id]
    @image = image_type.constantize.new
    @image.imageable = resource

    @image.image = params[:image][:image]

    ## Setting redirect url
    @redirect_url = params[:redirect_url] || root_url

    ## Validating the data
    @image.valid?

    respond_to do |format|
      if @image.errors.blank?

        # Saving the admin object
        @image.save

        # Setting the flash message
        message = translate("forms.created_successfully", :item => "Image")
        store_flash_message(message, :success)

        format.html {
          redirect_to @redirect_url, notice: message
        }
        format.json { render json: @image, status: :created, location: @admin }
        format.js {}
      else

        # Setting the flash message
        message = @image.errors.full_messages.to_sentence
        store_flash_message(message, :alert)

        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # PUT /super_admin/images/1
  # PUT /super_admin/images/1.js
  # PUT /super_admin/images/1.json
  def update

    # Get the image object and assign new image path to it
    image_type = params[:image_type] || "Image::Base"
    @image = image_type.constantize.find(params[:id])

    @image.image = params[:image][:image]
    @redirect_url = params[:redirect_url] || root_url

    ## Validating the data
    @image.valid?

    respond_to do |format|
      if @image.errors.blank?

        # Saving the admin object
        @image.save

        # Setting the flash message
        message = translate("forms.created_successfully", :item => "Image")
        store_flash_message(message, :success)

        format.html {
          redirect_to @redirect_url, notice: message
        }
        format.json { render json: @image, status: :created, location: @image }
        format.js {}
      else

        # Setting the flash message
        message = @image.errors.full_messages.to_sentence
        store_flash_message(message, :alert)

        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

end

app/controllers/super_admin/sessions_controller.rb
class SuperAdmin::SessionsController < SuperAdmin::BaseController

  skip_before_filter :require_super_admin, :except => :sign_out
  before_filter :redirect_if_signed_in, :only => :sign_in

  def sign_in

  end

  ## This method will accept a proc, execute it and render the json
  def create_session

    # Fetching the user data (email / username is case insensitive.)
    @authenticated, @super_admin, @heading, @alert = SuperAdmin.authenticate(params[:login_handle], params[:password])

    if @authenticated
      store_flash_message("#{@heading}: #{@alert}", :success)
      session[:super_admin_id] = @super_admin.id
      redirect_to redirect_url_after_sign_in
    else
      store_flash_message("#{@heading}: #{@alert}", :error)
      redirect_to redirect_url_if_sign_in_fails
    end

  end

  def sign_out

    @heading = translate("authentication.success")
    @alert = translate("authentication.logged_out_successfully")
    store_flash_message("#{@heading}: #{@alert}", :notice)

    # Reseting the auth token for user when he logs out.
    @current_super_admin.update_attribute :auth_token, SecureRandom.hex

    session.delete(:super_admin_id)

    redirect_to redirect_url_after_sign_out

  end

end

app/controllers/super_admin_controller.rb
class SuperAdminController < ApplicationController
  
  layout 'super_admin'
  
end

app/views/super_admin/deities/_edit.html.erb
<%# Used to add a Deity %>
<div class="box p-10">
  <div class="p-10 text-color-grey fs-18 mb-20">
    Edit Deity
  </div>
  <%= render 'form' %>
</div>

app/views/super_admin/deities/_form.html.erb
<%# Renders a partial which is used to create a new deity %>

<%= form_for([:super_admin, @deity], :html => {:id=>"form_deity", :class=>"mb-0 form-horizontal", :role => "form", :method => (@deity.new_record? ? :post : :put), :remote=>true}) do |f| %>

  <div class="modal-body">

    <%= @deity.errors[:base].to_sentence %>

    <%= hidden_field_tag :faction, @deity.new_record? ? super_admin_deities_path : super_admin_deities_path(@deity) %>
    <%= hidden_field_tag :fmethod, @deity.new_record? ? "POST" : "PUT" %>
    <%= hidden_field_tag :called_from, params[:called_from] if params[:called_from] %>

    <div class="form-inputs">


      <!-- Name (string) -->
      <%= render :partial=>"field", :locals=>{:object=>@deity,
                                              :object_name=>'deity',
                                              :field_name=>'name',
                                              :display_name=>'Name',
                                              :field_type=>'string',
                                              :input_type=>'text',
                                              :required=>true,
                                              :place_holder=>"e.g: Put a suitable example here."} %>

      <%= render :partial=>"field", :locals=>{:object=>@deity,
                                              :object_name=>'deity',
                                              :field_name=>'unicode_name',
                                              :display_name=>'Unicode Name',
                                              :field_type=>'string',
                                              :input_type=>'text',
                                              :required=>false,
                                              :place_holder=>"e.g: Kshetrapalan."} %>

      <!-- Temple (integer) -->
      <% if params[:called_from] && @temple && @temple.id %>
        <div class="form-inputs">
          <!-- Trust (Drop Down) -->
          <div class="form-group ">
            <label for="inp_temple" class="col-md-4 control-label">Choose a Temple
              <span class="text-color-red ml-10 pull-right">*</span>
            </label>
            <div class="col-md-8">
              <%= @deity.temple.display_name %>
            </div>
          </div>
        </div><!-- /.form-inputs -->
        <%= hidden_field_tag "deity[temple_id]", @temple.id %>
      <% else %>
        <div class="form-inputs">

          <div class="form-group ">
            <label for="inp_product" class="col-md-4 control-label">Choose a Temple
              <span class="text-color-red margin-left-10 margin-right-5 pull-right">*</span>
            </label>
            <div class="col-md-8">
              <%= collection_select(:deity, :temple_id, Temple.select("id, name, unicode_name").all, :id, :display_name, {:prompt=>true}, {:class => 'form-control required', :id=>"inp_temple"}) %>
            </div>
          </div>

        </div><!-- /.form-inputs -->
      <% end %>

      <!-- Description (text) -->
      <%= render :partial=>"field", :locals=>{:object=>@deity,
                                              :object_name=>'deity',
                                              :field_name=>'description',
                                              :display_name=>'Description',
                                              :field_type=>'text',
                                              :input_type=>'textarea',
                                              :required=>false,
                                              :place_holder=>"e.g: Put a suitable example here."} %>

    </div>

  </div>

  <div class="modal-footer">

    <div class="pull-right">
      <% button_text = "#{@deity.new_record? ? "Create" : "Update"} Item" %>
			<%# if @deity.new_record? %>
				<%#= link_to "Cancel", "#", :class => "btn", :remote=>true %>
			<%# else %>
				<%#= link_to 'Back', super_admin_deities_path, :class=>"btn ml-10", :remote => true unless @deity.new_record? %>
			<%# end %>
      <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      <%= submit_tag button_text, "data-reset-text"=>button_text, "data-loading-text"=>"Saving ...", :class=>"btn btn-primary ml-10" %>
    </div>

  </div>

	<div class="cl-10"></div>

<% end %>

app/views/super_admin/deities/_index.html.erb
<%# Displays list of @deities %>
<div id="div_deity_collections">
	<% @deities.each do |deity| %>
		<div id="div_deity_<%= deity.id %>">
			<%= render :partial=>"item", :locals=>{:deity=>deity} %>
		</div>
	<% end %>
	<% if @deities.blank? %>
		<div id="div_deity_empty" class="box text-color-grey p-80 text-align-center" style="height:200px;">
      <%= translate("forms.no_results_found") %>
		</div>
	<% end %>
</div>
<div class="cl"></div>

<% if @deities.any? %>
   <%= content_tag :div, :class=>"pull-right" do %>
     <%= paginate @deities, :remote => true %>
   <% end %>
<% end %>
<div class="cl"></div>

app/views/super_admin/deities/_item.html.erb
<%# describes about each deity %>
<div class="box hoverable p-10 box-border-black">

  <div class="row">
    <div class="col-md-2 visible-md visible-lg" style="padding-left:0px;padding-right:0px">
      <%= link_to display_thumbnail(deity, :deity_picture), super_admin_deity_path(deity), :remote=>true %>
    </div>
    <div class="col-md-10">
      <%= link_to deity.display_name, super_admin_deity_path(deity),
          :remote=>true, :class=>"heading3" %><br/>

      <div class="content"><%= deity.temple.display_name %></div>

      <div class="mt-10 pull-right text-color-gray fs-11 visible-md visible-lg">
        <%= display_time(deity.created_at) %>
      </div>
  	</div>
  </div>

  <div class="cl"></div>

</div>

app/views/super_admin/deities/_new.html.erb
<%# Used to create a new Deity %>
<div class="box p-10">
  <div class="p-10 text-color-blue fs-18 mb-20">
    Create a New Deity
  </div>
	<%= render 'form' %>
</div>

app/views/super_admin/deities/_show.html.erb
<%# Displays a detailed view of the deity %>
<%# Display Flash Message if any only in case of ajax request %>
<% if request.xhr? %>
	<%= render :partial=>"layouts/common/flash_message" %>
<% end %>

<div class="box p-10">

  <div class="row">
    <div class="col-md-3" style="padding-left:0px;padding-right:0px">
      <%= link_to display_thumbnail(@deity, :deity_picture),
                  upload_image_link(@deity, super_admin_deity_path(@deity), :deity_picture),
                  :remote => true %>
      <%= link_to "Change Image", upload_image_link(@deity, super_admin_deity_path(@deity), :deity_picture), :remote => true, :style=>"font-size:12px;" %>
    </div>

    <div class="col-md-9">
      <div class="heading1"><%= @deity.display_name %></div>
      <div class="heading2"><%= link_to @deity.temple.display_name, super_admin_temple_path(@deity.temple), class: "text-color-red" %></div>
    </div>
  </div>

  <div class="cl-20"></div>

  <div class="palette-footer ml-10">
    <%= link_to raw("<i class=\"icon-pencil icon-white mr--5\"></i> Edit"), edit_super_admin_deity_path(@deity), :class=>"btn btn-default btn-sm pull-right ml-10", :remote=>true %>
    <%= link_to raw("<i class=\"icon-remove \"></i> Delete"), super_admin_deity_path(@deity), method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-sm pull-right", :remote=>true %>
    <div class="cl-10"></div>
  </div>

  <div class="cl-20"></div>

  <%= content_tag :h3, "About the Deity", :class=>"heading" %>
  <hr>
  <div class='italic m-10'><%= simple_format(@deity.description.blank? ? "Description not available" : @deity.description) %></div>

  <%= content_tag :h3, "Details", :class=>"heading" %>

  <table class="table table-condensed table-hover table-striped mt-20">
    <tbody>
      <tr>
        <td class="bold" style="width:30%;">Created at</td>
        <td><%= display_time(@deity.created_at, "text-color-grey") %></td>
      </tr>
      <tr>
        <td class="bold" style="width:30%;">Last updated at</td>
        <td><%= display_time(@deity.updated_at, "text-color-grey") %></td>
      </tr>
    </tbody>
  </table>

</div>

app/views/super_admin/deities/_summary.html.erb
<%# Displays Total number of items in the system %>
<%# Display Flash Message if any only in case of ajax request %>
<% if request.xhr? %>
	<%= render :partial=>"layouts/common/flash_message" %>
<% end %>

<div class="box text-color-grey p-80 text-align-center" style="height:200px;">
  Total Deities = <%= Deity.count %>
</div>

app/views/super_admin/deities/destroy.js.erb
<% if @deity %>
  <% if @deity.new_record? %>

  	// Fill the right box with first deity details
  	$('#div_deity_details').html("<%= escape_javascript(render(:partial=>'summary')) %>");

  <% else %>

  	// Render the show partial to show flash message
  	$('#div_deity_details').html("<%= escape_javascript(render(:partial=>'show')) %>");

  <% end %>

  // Render deities List
  $('#div_deity_collections').html("<%= escape_javascript(render(:partial=>'index')) %>");

<% else %>

  var noResultsText = "<div id=\"div_admin_empty\" class=\"box text-color-grey p-80 text-align-center\" style=\"height:200px;\"><%= translate("forms.no_results_found") %></div>";
  $('#div_deity_index').html(noResultsText);
  $('#div_deity_details').html(noResultsText);

<% end %>

app/views/super_admin/deities/edit.js.erb
// Show the edit form in the right box.
heading = "Edit Deity";
bodyContent = "<%= escape_javascript(render(:partial=>"form")) %>";
showModal(heading, bodyContent);
validateDeityForm();

app/views/super_admin/deities/index.html.erb
<div class="cl-10 hidden-xs"></div>

<%# Displays to Manage the items %>
<div class="row mb-10">
	<div class="fs-22 col-sm-6 hidden-xs">Manage Deities</div>
	<div class="fs-22 col-sm-6 text-align-center visible-xs">Manage Deities</div>
	<div id="div_deity_filters" class="col-sm-6 hidden-xs">
		<%= render :partial=>"filters" %>
	</div>
</div>

<div class="cl-10 hidden-xs"></div>

<%# Renders a partial to display all the deities %>
<div class="row">
	<div id="div_deity_index" class="col-sm-6 hidden-xs">
		<%= render :partial=>"index" %>
	</div>
	<div id="div_deity_drop_down" class="col-xs-12 visible-xs">
		<%= render :partial=>"drop_down" %>
	</div>

	<div id="div_deity_details" class="col-xs-12 col-sm-6">
		<% case	params[:action] %>
		<% when "new", "edit", "show" %>
			<%= render :partial=>params[:action] %>
		<% when "index" %>
			<% if @deities.empty? %>
				<%= render :partial=>"summary" %>
			<% else %>
				<%= render :partial=>"show" %>
			<% end %>
		<% else %>
			<%= render :partial=>"summary" %>
		<% end %>
	</div>

</div>

app/views/super_admin/deities/index.js.erb
<% if @deities.any? %>

	// Fill the right box with first deity details in the list
	$('#div_deity_details').html("<%= escape_javascript(render(:partial=>'show')) %>");

	// Rendering the item list
	$('#div_deity_index').html("<%= escape_javascript(render(:partial=>"index")) %>");
	$('#div_deity_drop_down').html("<%= escape_javascript(render(:partial=>"drop_down")) %>");

<% else %>

	var noResultsText = "<div id=\"div_admin_empty\" class=\"box text-color-grey p-80 text-align-center\" style=\"height:200px;\"><%= translate("forms.no_results_found") %></div>";
	$('#div_deity_index').html(noResultsText);
	$('#div_deity_details').html(noResultsText);

<% end %>

app/views/super_admin/deities/new.js.erb
// Show the new form in the pop up form.
heading = "Create Deity";
bodyContent = "<%= escape_javascript(render(:partial=>"form")) %>";
showModal(heading, bodyContent);
validateDeityForm();

app/views/super_admin/deities/show.js.erb
// Fill the right box with deity details
$('#div_deity_details').html("<%= escape_javascript(render(:partial=>'show')) %>");

app/views/super_admin/deities/update.js.erb
<% if @deity.errors.blank? %>
	
	// Fill the right box with first item details
  $('#div_deity_details').html("<%= escape_javascript(render(:partial=>"show")) %>");
	
	// Refresh the updated item in the list
  $("#div_deity_<%= @deity.id %>").html("<%= escape_javascript(render :partial => 'item', :locals => { :deity => @deity }) %>")
  
  // Close Modal
  closeModal();

<% else %>
	
  // Show the new form in the pop up form.
  heading = "Edit Deity";
  bodyContent = "<%= escape_javascript(render(:partial=>"form")) %>";
  showModal(heading, bodyContent);
  validateDeityForm();
  
  // Populate Server Side Errors
  errorMessages = <%= @deity.errors.full_messages.to_json.html_safe %>;
  populateServerSideErrors('deity', errorMessages);

<% end %>