config/routes.rb
Rails.application.routes.draw do

  namespace(:trust_admin){ resources :offerings }
  root :to => 'welcome#index'

  namespace(:super_admin){
    resources :trust_admins
    resources :trusts
    resources :temples
    resources :deities
    resources :images
  }

  namespace(:trust_admin){
    resources :deities do
      resources :offerings
    end
  }

  get     'super_admin/sign_in'         => "super_admin/sessions#sign_in",         :as => :super_admin_sign_in
  post    'super_admin/create_session'  => "super_admin/sessions#create_session",  :as => :super_admin_create_session
  delete  'super_admin/sign_out'        => "super_admin/sessions#sign_out",        :as => :super_admin_sign_out

  get     'super_admin/home'           => "super_admin/home#index",                :as => :super_admin_home

  get     'trust_admin/sign_in'         => "trust_admin/sessions#sign_in",         :as => :trust_admin_sign_in
  post    'trust_admin/create_session'  => "trust_admin/sessions#create_session",  :as => :trust_admin_create_session
  delete  'trust_admin/sign_out'        => "trust_admin/sessions#sign_out",        :as => :trust_admin_sign_out

  get     'trust_admin/home'           => "trust_admin/home#index",                :as => :trust_admin_home

end

app/controllers/super_admin/base_controller.rb
class SuperAdmin::BaseController < ApplicationController

  before_filter :require_super_admin
  layout 'super_admin'

  protected

  def current_super_admin
    @current_super_admin ||= SuperAdmin.find_by_id(session[:super_admin_id])
  end

  def store_session
    session[:super_admin_id] = @current_super_admin.id
  end

  def require_super_admin
    unless current_super_admin
      @heading = translate("authentication.error")
      @alert = translate("authentication.invalid_token")
      store_flash_message("#{@heading}: #{@alert}", :errors)
      redirect_to super_admin_sign_in_url
    end
  end

  def redirect_url_if_sign_in_fails
    super_admin_sign_in_url
  end

  def redirect_url_after_sign_in
    super_admin_home_url
  end

  def redirect_url_after_sign_out
    super_admin_sign_in_url
  end

  def redirect_if_signed_in
    redirect_to redirect_url_after_sign_in if current_super_admin
  end

  def redirect_unless_signed_in
    redirect_to redirect_url_if_sign_in_fails unless current_super_admin
  end

end

app/controllers/super_admin/deities_controller.rb
class SuperAdmin::DeitiesController < SuperAdmin::BaseController

  before_filter :parse_pagination_params, :only=>:index
  before_filter :set_navs

  # GET /deities
  # GET /deities.js
  # GET /deities.json
  def index

    get_collections

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @deities }
      format.js {}
    end
  end

  # GET /deities/1
  # GET /deities/1.js
  # GET /deities/1.json
  def show
    ## Creating the deity object
    @deity = Deity.find(params[:id])

    respond_to do |format|
      format.html { get_collections and render :index }
      format.json { render json: @deity }
      format.js {}
    end
  end

  # GET /deities/new
  # GET /deities/new.json
  def new
    ## Intitializing the deity object
    @deity = Deity.new

    if params[:temple_id]
      @temple = Temple.find_by_id(params[:temple_id])
      @deity.temple = @temple
    end

    respond_to do |format|
      format.html { get_collections and render :index }
      format.json { render json: @deity }
      format.js {}
    end
  end

  # GET /deities/1/edit
  def edit
    ## Fetching the deity object
    @deity = Deity.find(params[:id])

    respond_to do |format|
      format.html { get_collections and render :index }
      format.json { render json: @deity }
      format.js {}
    end
  end

  # POST /deities
  # POST /deities.js
  # POST /deities.json
  def create
    ## Creating the deity object
    @deity = Deity.new(deity_params)

    if params[:deity] && params[:deity][:temple_id]
      @temple = Temple.find_by_id(params[:deity][:temple_id])
      @deity.temple = @temple
      @deity.trust = @temple.trust
    end

    ## Validating the data
    @deity.valid?

    respond_to do |format|
      if @deity.errors.blank?

        # Saving the deity object
        @deity.save

        # Setting the flash message
        message = translate("forms.created_successfully", :item => "Deity")
        store_flash_message(message, :success)

        format.html {
          redirect_to super_admin_deity_url(@deity), notice: message
        }
        format.json { render json: @deity, status: :created, location: @deity }
        format.js {}
      else

        # Setting the flash message
        message = @deity.errors.full_messages.to_sentence
        store_flash_message(message, :alert)

        format.html { render action: "new" }
        format.json { render json: @deity.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # PUT /deities/1
  # PUT /deities/1.js
  # PUT /deities/1.json
  def update
    ## Fetching the deity
    @deity = Deity.find(params[:id])

    ## Updating the @deity object with params
    @deity.assign_attributes(deity_params)

    ## Validating the data
    @deity.valid?

    respond_to do |format|
      if @deity.errors.blank?

        # Saving the deity object
        @deity.save

        # Setting the flash message
        message = translate("forms.updated_successfully", :item => "Deity")
        store_flash_message(message, :success)

        format.html {
          redirect_to super_admin_deity_url(@deity), notice: message
        }
        format.json { head :no_content }
        format.js {}

      else

        # Setting the flash message
        message = @deity.errors.full_messages.to_sentence
        store_flash_message(message, :alert)

        format.html {
          render action: "edit"
        }
        format.json { render json: @deity.errors, status: :unprocessable_entity }
        format.js {}

      end
    end
  end

  # DELETE /deities/1
  # DELETE /deities/1.js
  # DELETE /deities/1.json
  def destroy
    ## Fetching the deity
    @deity = Deity.find(params[:id])

    respond_to do |format|
      ## Destroying the deity
      @deity.destroy
      @deity = Deity.new

      # Fetch the deities to refresh ths list and details box
      get_collections
      @deity = @deities.first if @deities and @deities.any?

      # Setting the flash message
      message = translate("forms.destroyed_successfully", :item => "Deity")
      store_flash_message(message, :success)

      format.html {
        redirect_to super_admin_deities_url notice: message
      }
      format.json { head :no_content }
      format.js {}

    end
  end

  private

  def set_navs
    set_nav("Manage Deities")
  end

  def get_collections
    # Fetching the deities
    relation = Deity.where("")
    @filters = {}

    if params[:query]
      @query = params[:query].strip
      relation = relation.search(@query) if !@query.blank?
    end

    @deities = relation.order("created_at desc").page(@current_page).per(@per_page)

    ## Initializing the @deity object so that we can render the show partial
    @deity = @deities.first unless @deity

    return true

  end

  def deity_params
    params.require(:deity).permit(:name, :unicode_name, :description, :temple_id, :trust_id)
  end

end

app/controllers/super_admin/home_controller.rb
class SuperAdmin::HomeController < SuperAdmin::BaseController

  before_filter :require_super_admin
  before_filter :set_navs, :only=>:index

  # GET /
  def index
  end

  private

  def set_navs
    set_nav("Home")
  end

end

app/controllers/super_admin/images_controller.rb
class SuperAdmin::ImagesController < SuperAdmin::BaseController

  # GET /super_admin/images/new
  # GET /super_admin/images/new.json

  skip_before_filter :set_navs, :parse_pagination_params

  def new
    ## Intitializing the image object

    image_type = params[:image_type] || "Image::Base"

    @image = image_type.constantize.new

    respond_to do |format|
      format.html { get_collections and render :index }
      format.json { render json: @image }
      format.js {}
    end
  end

  # GET /super_admin/images/1/edit
  # GET /super_admin/images/1/edit.js
  # GET /super_admin/images/1/edit.json

  def edit

    ## Fetching the image object
    image_type = params[:image_type] || "Image::Base"
    @image = image_type.constantize.find(params[:id])

    respond_to do |format|
      format.html { get_collections and render :index }
      format.json { render json: @image }
      format.js {}
    end
  end

  # POST /super_admin/images/
  # POST /super_admin/images.js
  # POST /super_admin/images.json
  def create

    ## Creating the image object
    image_type = params[:image_type] || "Image::Base"

    resource = params[:imageable_type].constantize.find params[:imageable_id]
    @image = image_type.constantize.new
    @image.imageable = resource

    @image.image = params[:image][:image]

    ## Setting redirect url
    @redirect_url = params[:redirect_url] || root_url

    ## Validating the data
    @image.valid?

    respond_to do |format|
      if @image.errors.blank?

        # Saving the admin object
        @image.save

        # Setting the flash message
        message = translate("forms.created_successfully", :item => "Image")
        store_flash_message(message, :success)

        format.html {
          redirect_to @redirect_url, notice: message
        }
        format.json { render json: @image, status: :created, location: @admin }
        format.js {}
      else

        # Setting the flash message
        message = @image.errors.full_messages.to_sentence
        store_flash_message(message, :alert)

        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # PUT /super_admin/images/1
  # PUT /super_admin/images/1.js
  # PUT /super_admin/images/1.json
  def update

    # Get the image object and assign new image path to it
    image_type = params[:image_type] || "Image::Base"
    @image = image_type.constantize.find(params[:id])

    @image.image = params[:image][:image]
    @redirect_url = params[:redirect_url] || root_url

    ## Validating the data
    @image.valid?

    respond_to do |format|
      if @image.errors.blank?

        # Saving the admin object
        @image.save

        # Setting the flash message
        message = translate("forms.created_successfully", :item => "Image")
        store_flash_message(message, :success)

        format.html {
          redirect_to @redirect_url, notice: message
        }
        format.json { render json: @image, status: :created, location: @image }
        format.js {}
      else

        # Setting the flash message
        message = @image.errors.full_messages.to_sentence
        store_flash_message(message, :alert)

        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

end

app/controllers/super_admin/sessions_controller.rb
class SuperAdmin::SessionsController < SuperAdmin::BaseController

  skip_before_filter :require_super_admin, :except => :sign_out
  before_filter :redirect_if_signed_in, :only => :sign_in

  def sign_in

  end

  ## This method will accept a proc, execute it and render the json
  def create_session

    # Fetching the user data (email / username is case insensitive.)
    @authenticated, @super_admin, @heading, @alert = SuperAdmin.authenticate(params[:login_handle], params[:password])

    if @authenticated
      store_flash_message("#{@heading}: #{@alert}", :success)
      session[:super_admin_id] = @super_admin.id
      redirect_to redirect_url_after_sign_in
    else
      store_flash_message("#{@heading}: #{@alert}", :error)
      redirect_to redirect_url_if_sign_in_fails
    end

  end

  def sign_out

    @heading = translate("authentication.success")
    @alert = translate("authentication.logged_out_successfully")
    store_flash_message("#{@heading}: #{@alert}", :notice)

    # Reseting the auth token for user when he logs out.
    @current_super_admin.update_attribute :auth_token, SecureRandom.hex

    session.delete(:super_admin_id)

    redirect_to redirect_url_after_sign_out

  end

end

app/controllers/super_admin/temples_controller.rb
class SuperAdmin::TemplesController < SuperAdmin::BaseController

  before_filter :parse_pagination_params, :only=>:index
  before_filter :set_navs

  # GET /temples
  # GET /temples.js
  # GET /temples.json
  def index

    get_collections

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @temples }
      format.js {}
    end
  end

  # GET /temples/1
  # GET /temples/1.js
  # GET /temples/1.json
  def show
    ## Creating the temple object
    @temple = Temple.find(params[:id])

    respond_to do |format|
      format.html { get_collections and render :index }
      format.json { render json: @temple }
      format.js {}
    end
  end

  # GET /temples/new
  # GET /temples/new.json
  def new
    ## Intitializing the temple object
    @temple = Temple.new

    if params[:trust_id]
      @trust = Trust.find_by_id(params[:trust_id])
      @temple.trust = @trust
    end

    respond_to do |format|
      format.html { get_collections and render :index }
      format.json { render json: @temple }
      format.js {}
    end
  end

  # GET /temples/1/edit
  def edit
    ## Fetching the temple object
    @temple = Temple.find(params[:id])

    respond_to do |format|
      format.html { get_collections and render :index }
      format.json { render json: @temple }
      format.js {}
    end
  end

  # POST /temples
  # POST /temples.js
  # POST /temples.json
  def create
    ## Creating the temple object
    @temple = Temple.new(temple_params)

    ## Validating the data
    @temple.valid?

    respond_to do |format|
      if @temple.errors.blank?

        # Saving the temple object
        @temple.save
        @trust = @temple.trust

        # Setting the flash message
        message = translate("forms.created_successfully", :item => "Temple")
        store_flash_message(message, :success)

        format.html {
          redirect_to super_admin_temple_url(@temple), notice: message
        }
        format.json { render json: @temple, status: :created, location: @temple }
        format.js {}
      else

        # Setting the flash message
        message = @temple.errors.full_messages.to_sentence
        store_flash_message(message, :alert)

        format.html { render action: "new" }
        format.json { render json: @temple.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # PUT /temples/1
  # PUT /temples/1.js
  # PUT /temples/1.json
  def update
    ## Fetching the temple
    @temple = Temple.find(params[:id])

    ## Updating the @temple object with params
    @temple.assign_attributes(temple_params)

    ## Validating the data
    @temple.valid?

    respond_to do |format|
      if @temple.errors.blank?

        # Saving the temple object
        @temple.save

        # Setting the flash message
        message = translate("forms.updated_successfully", :item => "Temple")
        store_flash_message(message, :success)

        format.html {
          redirect_to super_admin_temple_url(@temple), notice: message
        }
        format.json { head :no_content }
        format.js {}

      else

        # Setting the flash message
        message = @temple.errors.full_messages.to_sentence
        store_flash_message(message, :alert)

        format.html {
          render action: "edit"
        }
        format.json { render json: @temple.errors, status: :unprocessable_entity }
        format.js {}

      end
    end
  end

  # DELETE /temples/1
  # DELETE /temples/1.js
  # DELETE /temples/1.json
  def destroy
    ## Fetching the temple
    @temple = Temple.find(params[:id])

    respond_to do |format|
      ## Destroying the temple
      @temple.destroy
      @temple = Temple.new

      # Fetch the temples to refresh ths list and details box
      get_collections
      @temple = @temples.first if @temples and @temples.any?

      # Setting the flash message
      message = translate("forms.destroyed_successfully", :item => "Temple")
      store_flash_message(message, :success)

      format.html {
        redirect_to super_admin_temples_url notice: message
      }
      format.json { head :no_content }
      format.js {}

    end
  end

  private

  def set_navs
    set_nav("Manage Temples")
  end

  def get_collections
    # Fetching the temples
    relation = Temple.where("")
    @filters = {}

    if params[:query]
      @query = params[:query].strip
      relation = relation.search(@query) if !@query.blank?
    end

    @temples = relation.order("created_at desc").page(@current_page).per(@per_page)

    ## Initializing the @temple object so that we can render the show partial
    @temple = @temples.first unless @temple

    return true

  end

  def temple_params
    params.require(:temple).permit(:name, :unicode_name, :trust_id, :description)
  end

end

app/controllers/super_admin_controller.rb
class SuperAdminController < ApplicationController
  
  layout 'super_admin'
  
end

app/views/super_admin/trusts/_drop_down.html.erb
<div class="btn-group mt-10 mb-10" style="width:100%;">
  <button type="button" class="btn btn-default btn-block dropdown-toggle" data-toggle="dropdown">
    Choose a Trust <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <% @trusts.each do |trust| %>
      <li><%= link_to trust.display_name, super_admin_trust_path(trust), :remote=>true %></li>
    <% end %>
    <%= content_tag :li, link_to_next_page(@trusts, 'Next Page', :remote => true) %>
    <%= content_tag :li, link_to_previous_page(@trusts, 'Previous Page', :remote => true) %>
  </ul>
</div>

app/views/super_admin/trusts/_field.html.erb
<%
  unless defined?(required)
    required = false
  end
  unless defined?(place_holder)
    place_holder = ""
  end
  inp_id = "inp_#{display_name.underscore.split(" ").join("_")}"
  error_class = object.errors[field_name.to_s].any? ? "has-error" : ""
%>

<div class="form-group <%= error_class %>">

  <% if ["text", "email", "search", "password", "date", "time", "tel", "url", "month", "file", "image", ""].include?(input_type) %>

    <label for="inp_<%= display_name.underscore.split(" ").join("_") %>" class="col-md-4 control-label">
      <%= display_name %>
      <span class="text-color-red ml-10 mr--5 pull-right"><%= required ? "*" : raw("&nbsp;&nbsp;") %></span>
    </label>
    <div class="col-md-8">
      <input name="<%= object_name %>[<%= field_name %>]" id="inp_<%= display_name.underscore.split(" ").join("_") %>" class="text input form-control" type="<%= input_type %>" placeholder="<%= place_holder %>" value="<%= object.send(field_name.to_s) %>" />
    </div>

  <% elsif input_type == "checkbox" %>

    <label for="inp_<%= display_name.underscore.split(" ").join("_") %>" class="col-md-4 control-label">
      <%= display_name %>
      <span class="text-color-red ml-10 mr--5 pull-right"><%= required ? "*" : raw("&nbsp;&nbsp;") %></span>
    </label>
    <div class="col-md-8">
      <input name="<%= object_name %>[<%= field_name %>]" id="inp_<%= display_name.underscore.split(" ").join("_") %>" type="<%= input_type %>" class="checkbox input form-control" <%= object.send(field_name.to_s) ? "checked='checked'" : "" %> />
    </div>

  <% elsif input_type == "textarea" %>

    <label for="inp_<%= display_name.underscore.split(" ").join("_") %>" class="col-md-4 control-label">
      <%= display_name %>
      <span class="text-color-red ml-10 mr--5 pull-right"><%= required ? "*" : raw("&nbsp;&nbsp;") %></span>
    </label>
    <div class="col-md-8">
      <textarea name="<%= object_name %>[<%= field_name %>]" style="height:200px;" class="textarea input form-control" id="inp_<%= display_name.underscore.split(" ").join("_") %> placeholder="<%= place_holder %>" "><%= object.send(field_name.to_s) %></textarea>
    </div>

  <% end %>

</div>

app/views/super_admin/trusts/_filters.html.erb
<div class="row">
  <div class="col-xs-4">
    <%= link_to raw("<i class='icon-plus icon-white mr--5'></i> New Trust"), new_super_admin_trust_path, :class=>"btn btn-lg btn-warning", :remote=>true %>
  </div><!-- /.col-xs-6 -->

  <div class="col-xs-8">

    <%= form_for Trust.new, :url => super_admin_trusts_path, :method => :get, :remote=>true, :html=>{:class=>"pull-right", :style=>"m-bottom:0px;"} do |f| %>

    <div class="input-group">
      <input type="text" name="query" placeholder="Search Trusts ..." class="form-control search">
      <span class="input-group-btn">
        <button type="submit" class="btn btn-lg btn-primary">Search!</button>
      </span>
    </div><!-- /input-group -->

    <%- end %>

  </div><!-- /.col-xs-6 -->
</div><!-- /.row -->

app/views/super_admin/trusts/_index.html.erb
<%# Displays list of @trusts %>
<div id="div_trust_collections">
	<% @trusts.each do |trust| %>
		<div id="div_trust_<%= trust.id %>">
			<%= render :partial=>"item", :locals=>{:trust=>trust} %>
		</div>
	<% end %>
	<% if @trusts.blank? %>
		<div id="div_trust_empty" class="box text-color-grey p-80 text-align-center" style="height:200px;">
      <%= translate("forms.no_results_found") %>
		</div>
	<% end %>
</div>
<div class="cl"></div>

<% if @trusts.any? %>
   <%= content_tag :div, :class=>"pull-right" do %>
     <%= paginate @trusts, :remote => true %>
   <% end %>
<% end %>
<div class="cl"></div>

app/views/super_admin/trusts/_item.html.erb
<%# describes about each trust %>
<div class="box hoverable p-10 box-border-black">

  <div class="row">
    <div class="col-md-2 visible-md visible-lg" style="padding-left:0px;padding-right:0px">
      <%= link_to display_thumbnail(trust, :trust_logo), super_admin_trust_path(trust), :remote=>true %>
    </div>
    <div class="col-md-10">
      <%= link_to trust.display_name, super_admin_trust_path(trust), :remote=>true, :class=>"heading3" %><br/>

      <div class="content"><%= scrap_word(trust.description, 100) %></div>

      <div class="mt-10 pull-right text-color-gray fs-11 visible-md visible-lg">
        <%= display_time(trust.created_at) %>
      </div>
  	</div>
  </div>

  <div class="cl"></div>

</div>

app/views/super_admin/trusts/_new.html.erb
<%# Used to create a new Trust %>
<div class="box p-10">
  <div class="p-10 text-color-blue fs-18 mb-20">
    Create a New Trust
  </div>
	<%= render 'form' %>
</div>

app/views/super_admin/trusts/_show.html.erb
<%# Displays a detailed view of the trust %>
<%# Display Flash Message if any only in case of ajax request %>
<% if request.xhr? %>
	<%= render :partial=>"layouts/common/flash_message" %>
<% end %>

<div class="box p-10">

  <div class="row">
    <div class="col-md-3" style="padding-left:0px;padding-right:0px">
      <%= link_to display_thumbnail(@trust, :trust_logo),
                  upload_image_link(@trust, super_admin_trust_path(@trust), :trust_logo),
                  :remote => true %>
      <%= link_to "Change Image", upload_image_link(@trust, super_admin_trust_path(@trust)), :remote => true, :style=>"font-size:12px;" %>
    </div>

    <div class="col-md-9">
      <div class="heading1"><%= @trust.display_name %></div>
    </div>
  </div>

  <div class="cl-20"></div>

  <div class="palette-footer ml-10">
    <%= link_to raw("<i class=\"icon-pencil icon-white mr--5\"></i> Edit"), edit_super_admin_trust_path(@trust), :class=>"btn btn-default btn-sm pull-right ml-10", :remote=>true %>
    <%= link_to raw("<i class=\"icon-remove \"></i> Delete"), super_admin_trust_path(@trust), method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-sm pull-right", :remote=>true %>
    <div class="cl-10"></div>
  </div>

  <hr>

  <%= content_tag :h3, "About the Trust", :class=>"heading mb-20" %>
  <div class='italic m-10'><%= simple_format(@trust.description.blank? ? "Description not available" : @trust.description) %></div>

  <%= content_tag :h3, "Details", :class=>"heading" %>

  <table class="table table-condensed table-hover table-striped mt-20">
    <tbody>
      <tr>
        <td class="bold" style="width:30%;">Email</td>
        <td><%= @trust.email.blank? ? "-" : @trust.email %></td>
      </tr>
      <tr>
        <td class="bold" style="width:30%;">Phone</td>
        <td><%= @trust.phone.blank? ? "-" : @trust.phone %></td>
      </tr>
      <tr>
        <td class="bold" style="width:30%;">Status</td>
        <td><%= @trust.display_status %></td>
      </tr>
      <tr>
        <td class="bold" style="width:30%;">Created at</td>
        <td><%= display_time(@trust.created_at, "text-color-grey") %></td>
      </tr>
      <tr>
        <td class="bold" style="width:30%;">Last updated at</td>
        <td><%= display_time(@trust.updated_at, "text-color-grey") %></td>
      </tr>
    </tbody>
  </table>

  <%= content_tag :h3, "Admin", :class=>"heading pull-left" %>
  <%= link_to raw("<i class='icon-plus icon-white mr--5'></i> New Admin"), new_super_admin_trust_admin_path(called_from: "trust_show", trust_id: @trust.id), :class=>"btn btn-warning pull-right mb-20 mt-10", :remote=>true %>
  <div class="cl"></div>
  <hr>

  <% @trust.trust_admins.each do |ta| %>
    <div class="row pb-10">
      <div class="col-md-2 visible-md visible-lg" style="padding-left:0px;padding-right:0px">
        <%= link_to display_thumbnail(ta, :profile_picture), super_admin_trust_admin_path(ta) %>
      </div>
      <div class="col-md-10">
        <%= link_to ta.display_name, super_admin_trust_admin_path(ta), :class=>"heading3" %><br/>
        <div class="content"><%= ta.address if ta.address %></div>
      </div>
    </div>
  <% end %>


  <%= content_tag :h3, "Temples", :class=>"heading pull-left" %>
  <%= link_to raw("<i class='icon-plus icon-white mr--5'></i> New Temple"), new_super_admin_temple_path(called_from: "trust_show", trust_id: @trust.id), :class=>"btn btn-warning pull-right mb-20 mt-10", :remote=>true %>
  <div class="cl"></div>
  <hr>

  <% @trust.temples.each do |temple| %>
    <div class="row pb-10">
      <div class="col-md-2 visible-md visible-lg" style="padding-left:0px;padding-right:0px">
        <%= link_to display_thumbnail(temple, :temple_picture), super_admin_temple_path(temple) %>
      </div>
      <div class="col-md-10">
        <%= link_to temple.display_name, super_admin_temple_path(temple), :class=>"heading3" %><br/>
        <div class="content"><%= scrap_word(temple.description, 200) if temple.description %></div>
      </div>
    </div>
  <% end %>

</div>

app/views/super_admin/trusts/_summary.html.erb
<%# Displays Total number of items in the system %>
<%# Display Flash Message if any only in case of ajax request %>
<% if request.xhr? %>
	<%= render :partial=>"layouts/common/flash_message" %>
<% end %>

<div class="box text-color-grey p-80 text-align-center" style="height:200px;">
  Total Trusts = <%= Trust.count %>
</div>

app/views/super_admin/trusts/create.js.erb
<% if @trust.errors.blank? %>
	
	// Fill the right box with first trust details
	$('#div_trust_details').html("<%= escape_javascript(render(:partial=>'show')) %>");
	
	// Add the newly created item to the list
  $("#div_trust_collections").prepend("<div id=\"div_trust_<%= @trust.id %>\"><%= escape_javascript(render(:partial => 'item', :locals => { :trust => @trust })) %></div>")
  $("#div_trust_empty").hide();
  
  // Close Modal
  closeModal();

<% else %>
	
  // Show the new form in the pop up form.
  heading = "Create Trust";
  bodyContent = "<%= escape_javascript(render(:partial=>"form")) %>";
  showModal(heading, bodyContent);
  validateTrustForm();
  
  // Populate Server Side Errors
  errorMessages = <%= @trust.errors.full_messages.to_json.html_safe %>;
  populateServerSideErrors('trust', errorMessages);
	
<% end %>

app/views/super_admin/trusts/destroy.js.erb
<% if @trust %>
  <% if @trust.new_record? %>

  	// Fill the right box with first trust details
  	$('#div_trust_details').html("<%= escape_javascript(render(:partial=>'summary')) %>");

  <% else %>

  	// Render the show partial to show flash message
  	$('#div_trust_details').html("<%= escape_javascript(render(:partial=>'show')) %>");

  <% end %>

  // Render trusts List
  $('#div_trust_collections').html("<%= escape_javascript(render(:partial=>'index')) %>");

<% else %>

  var noResultsText = "<div id=\"div_admin_empty\" class=\"box text-color-grey p-80 text-align-center\" style=\"height:200px;\"><%= translate("forms.no_results_found") %></div>";
  $('#div_trust_index').html(noResultsText);
  $('#div_trust_details').html(noResultsText);

<% end %>

app/views/super_admin/trusts/show.js.erb
// Fill the right box with trust details
$('#div_trust_details').html("<%= escape_javascript(render(:partial=>'show')) %>");