config/routes.rb
Rails.application.routes.draw do

  namespace(:trust_admin){ resources :offerings }
  root :to => 'welcome#index'

  namespace(:super_admin){
    resources :trust_admins
    resources :trusts
    resources :temples
    resources :deities
    resources :images
  }

  namespace(:trust_admin){
    resources :deities do
      resources :offerings
    end
  }

  get     'super_admin/sign_in'         => "super_admin/sessions#sign_in",         :as => :super_admin_sign_in
  post    'super_admin/create_session'  => "super_admin/sessions#create_session",  :as => :super_admin_create_session
  delete  'super_admin/sign_out'        => "super_admin/sessions#sign_out",        :as => :super_admin_sign_out

  get     'super_admin/home'           => "super_admin/home#index",                :as => :super_admin_home

  get     'trust_admin/sign_in'         => "trust_admin/sessions#sign_in",         :as => :trust_admin_sign_in
  post    'trust_admin/create_session'  => "trust_admin/sessions#create_session",  :as => :trust_admin_create_session
  delete  'trust_admin/sign_out'        => "trust_admin/sessions#sign_out",        :as => :trust_admin_sign_out

  get     'trust_admin/home'           => "trust_admin/home#index",                :as => :trust_admin_home

end

app/models/offering.rb
class Offering < ActiveRecord::Base

  # Validations
  validates :name,
    :presence => true,
    :length => {:minimum => ConfigCenter::GeneralValidations::NAME_MIN_LEN ,
      :maximum => ConfigCenter::GeneralValidations::NAME_MAX_LEN},
      :format => {:with => ConfigCenter::GeneralValidations::NAME_FORMAT_REG_EXP}

  validates :price, presence: true, :numericality => {:greater_than => 0}
  validates :deity, presence: true
  validates :temple, presence: true

  validates :devaswam_share, presence: true
  validates :shanti_share, presence: true
  validates :kazhakam_share, presence: true

  validate :sum_of_shares

  def sum_of_shares
    if devaswam_share.present? && shanti_share.present? && kazhakam_share.present?
      if devaswam_share + shanti_share + kazhakam_share != price
        errors.add(:price, "doesn't match with the sum of Devaswam, Shanti and Kazhakam share")
      end
    end
  end

  def display_name
    unicode_name || name
  end

  # Associations
  belongs_to :deity
  belongs_to :temple

  # return an active record relation object with the search query in its where clause
  # Return the ActiveRecord::Relation object
  # == Examples
  #   >>> offering.search(query)
  #   => ActiveRecord::Relation object
  scope :search, lambda {|query| where("LOWER(name) LIKE LOWER('%#{query}%') OR\ LOWER(notes) LIKE LOWER('%#{query}%')") }

end

app/controllers/super_admin/trust_admins_controller.rb
class SuperAdmin::TrustAdminsController < SuperAdmin::BaseController

  before_filter :parse_pagination_params, :only=>:index
  before_filter :set_navs

  # GET /trust_admins
  # GET /trust_admins.js
  # GET /trust_admins.json
  def index

    get_collections

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trust_admins }
      format.js {}
    end
  end

  # GET /trust_admins/1
  # GET /trust_admins/1.js
  # GET /trust_admins/1.json
  def show
    ## Creating the trust admin object
    @trust_admin = TrustAdmin.find(params[:id])

    respond_to do |format|
      format.html { get_collections and render :index }
      format.json { render json: @trust_admin }
      format.js {}
    end
  end

  # GET /trust_admins/new
  # GET /trust_admins/new.json
  def new
    ## Intitializing the trust admin object
    @trust_admin = TrustAdmin.new
    if params[:trust_id]
      @trust = Trust.find_by_id(params[:trust_id])
      @trust_admin.trust = @trust
    end

    respond_to do |format|
      format.html { get_collections and render :index }
      format.json { render json: @trust_admin }
      format.js {}
    end
  end

  # GET /trust_admins/1/edit
  def edit
    ## Fetching the trust admin object
    @trust_admin = TrustAdmin.find(params[:id])

    respond_to do |format|
      format.html { get_collections and render :index }
      format.json { render json: @trust_admin }
      format.js {}
    end
  end

  # POST /trust_admins
  # POST /trust_admins.js
  # POST /trust_admins.json
  def create
    ## Creating the trust admin object
    @trust_admin = TrustAdmin.new(trust_admin_params)

    ## Validating the data
    @trust_admin.valid?

    respond_to do |format|
      if @trust_admin.errors.blank?

        # Saving the trust admin object
        @trust_admin.save
        @trust = @trust_admin.trust

        # Setting the flash message
        message = translate("forms.created_successfully", :item => "Admin")
        store_flash_message(message, :success)

        format.html {
          redirect_to super_admin_admin_url(@trust_admin), notice: message
        }
        format.json { render json: @trust_admin, status: :created, location: @trust_admin }
        format.js {}
      else

        # Setting the flash message
        message = @trust_admin.errors.full_messages.to_sentence
        store_flash_message(message, :alert)

        format.html { render action: "new" }
        format.json { render json: @trust_admin.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # PUT /trust_admins/1
  # PUT /trust_admins/1.js
  # PUT /trust_admins/1.json
  def update
    ## Fetching the trust admin
    @trust_admin = TrustAdmin.find(params[:id])

    ## Updating the @trust_admin object with params
    @trust_admin.assign_attributes(trust_admin_params)

    ## Validating the data
    @trust_admin.valid?

    respond_to do |format|
      if @trust_admin.errors.blank?

        # Saving the trust admin object
        @trust_admin.save

        # Setting the flash message
        message = translate("forms.updated_successfully", :item => "Admin")
        store_flash_message(message, :success)

        format.html {
          redirect_to super_admin_admin_url(@trust_admin), notice: message
        }
        format.json { head :no_content }
        format.js {}

      else

        # Setting the flash message
        message = @trust_admin.errors.full_messages.to_sentence
        store_flash_message(message, :alert)

        format.html {
          render action: "edit"
        }
        format.json { render json: @trust_admin.errors, status: :unprocessable_entity }
        format.js {}

      end
    end
  end

  # DELETE /trust_admins/1
  # DELETE /trust_admins/1.js
  # DELETE /trust_admins/1.json
  def destroy
    ## Fetching the trust admin
    @trust_admin = TrustAdmin.find(params[:id])

    respond_to do |format|
      ## Destroying the trust admin
      @trust_admin.destroy
      @trust_admin = TrustAdmin.new

      # Fetch the trust admins to refresh ths list and details box
      get_collections
      @trust_admin = @trust_admins.first if @trust_admins and @trust_admins.any?

      # Setting the flash message
      message = translate("forms.destroyed_successfully", :item => "Admin")
      store_flash_message(message, :success)

      format.html {
        redirect_to super_admin_admins_url notice: message
      }
      format.json { head :no_content }
      format.js {}

    end
  end

  private

  def set_navs
    set_nav("Manage Trust Admin")
  end

  def get_collections
    # Fetching the trust admins
    relation = TrustAdmin.where("")
    @filters = {}

    if params[:query]
      @query = params[:query].strip
      relation = relation.search(@query) if !@query.blank?
    end

    @trust_admins = relation.order("created_at desc").page(@current_page).per(@per_page)

    ## Initializing the @trust_admin object so that we can render the show partial
    @trust_admin = @trust_admins.first unless @trust_admin

    return true

  end

  def trust_admin_params
    params.require(:trust_admin).permit(:name, :unicode_name, :username, :status, :email, :phone, :address, :trust_id, :password, :password_confirmation)
  end

end

app/controllers/trust_admin/base_controller.rb
class TrustAdmin::BaseController < ApplicationController

  before_filter :require_trust_admin
  layout 'trust_admin'

  protected

  def current_trust_admin
    @current_trust_admin ||= TrustAdmin.find_by_id(session[:trust_admin_id])
  end

  def store_session
    session[:trust_admin_id] = @current_trust_admin.id
  end

  def require_trust_admin
    unless current_trust_admin
      @heading = translate("authentication.error")
      @alert = translate("authentication.invalid_token")
      store_flash_message("#{@heading}: #{@alert}", :errors)
      redirect_to trust_admin_sign_in_url
    end
  end

  def redirect_url_if_sign_in_fails
    trust_admin_sign_in_url
  end

  def redirect_url_after_sign_in
    trust_admin_home_url
  end

  def redirect_url_after_sign_out
    trust_admin_sign_in_url
  end

  def redirect_if_signed_in
    redirect_to redirect_url_after_sign_in if current_trust_admin
  end

  def redirect_unless_signed_in
    redirect_to redirect_url_if_sign_in_fails unless current_trust_admin
  end

end

app/controllers/trust_admin/home_controller.rb
class TrustAdmin::HomeController < TrustAdmin::BaseController

  before_filter :require_trust_admin
  before_filter :set_navs, :only=>:index

  # GET /
  def index
  end

  private

  def set_navs
    set_nav("Home")
  end

end

app/controllers/trust_admin/offerings_controller.rb
class TrustAdmin::OfferingsController < TrustAdmin::BaseController

  before_filter :require_trust_admin, :get_deity
  before_filter :parse_pagination_params, :only=> [:index, :destroy]
  before_filter :set_navs

  # GET /offerings
  # GET /offerings.js
  # GET /offerings.json
  def index

    get_collections

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offerings }
      format.js {}
    end
  end

  # GET /offerings/1
  # GET /offerings/1.js
  # GET /offerings/1.json
  def show
    ## Creating the offering object
    @offering = Offering.find(params[:id])

    respond_to do |format|
      format.html { get_collections and render :index }
      format.json { render json: @offering }
      format.js {}
    end
  end

  # GET /offerings/new
  # GET /offerings/new.json
  def new
    ## Intitializing the offering object
    @offering = Offering.new
    set_deity_and_temple

    respond_to do |format|
      format.html { get_collections and render :index }
      format.json { render json: @offering }
      format.js {}
    end
  end

  # GET /offerings/1/edit
  def edit
    ## Fetching the offering object
    @offering = Offering.find(params[:id])
    set_deity_and_temple

    respond_to do |format|
      format.html { get_collections and render :index }
      format.json { render json: @offering }
      format.js {}
    end
  end

  # POST /offerings
  # POST /offerings.js
  # POST /offerings.json
  def create
    ## Creating the offering object
    @offering = Offering.new(offering_params)

    set_deity_and_temple

    ## Validating the data
    @offering.valid?

    respond_to do |format|
      if @offering.errors.blank?

        # Saving the offering object
        @offering.save

        # Setting the flash message
        message = translate("forms.created_successfully", :item => "Offering")
        store_flash_message(message, :success)

        format.html {
          redirect_to trust_admin_offering_url(@offering), notice: message
        }
        format.json { render json: @offering, status: :created, location: @offering }
        format.js {}
      else

        # Setting the flash message
        message = @offering.errors.full_messages.to_sentence
        store_flash_message(message, :alert)

        format.html { render action: "new" }
        format.json { render json: @offering.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # PUT /offerings/1
  # PUT /offerings/1.js
  # PUT /offerings/1.json
  def update
    ## Fetching the offering
    @offering = Offering.find(params[:id])

    ## Updating the @offering object with params
    @offering.assign_attributes(offering_params)
    set_deity_and_temple

    ## Validating the data
    @offering.valid?

    respond_to do |format|
      if @offering.errors.blank?

        # Saving the offering object
        @offering.save

        # Setting the flash message
        message = translate("forms.updated_successfully", :item => "Offering")
        store_flash_message(message, :success)

        format.html {
          redirect_to trust_admin_offering_url(@offering), notice: message
        }
        format.json { head :no_content }
        format.js {}

      else

        # Setting the flash message
        message = @offering.errors.full_messages.to_sentence
        store_flash_message(message, :alert)

        format.html {
          render action: "edit"
        }
        format.json { render json: @offering.errors, status: :unprocessable_entity }
        format.js {}

      end
    end
  end

  # DELETE /offerings/1
  # DELETE /offerings/1.js
  # DELETE /offerings/1.json
  def destroy
    ## Fetching the offering
    @offering = Offering.find(params[:id])
    @deity = @offering.deity

    respond_to do |format|
      ## Destroying the offering
      @offering.destroy

      # Fetch the offerings to refresh ths list and details box
      get_collections

      # Setting the flash message
      message = translate("forms.destroyed_successfully", :item => "Offering")
      store_flash_message(message, :success)

      format.html {
        redirect_to trust_admin_offerings_url notice: message
      }
      format.json { head :no_content }
      format.js {}

    end
  end

  private

  def set_navs
    set_nav("Offering")
  end

  def get_collections

    # Fetching the offerings
    relation = @deity.offerings.where("")
    @filters = {}

    if params[:query]
      @query = params[:query].strip
      relation = relation.search(@query) if !@query.blank?
    end

    @offerings = relation.order("created_at desc").page(@current_page).per(@per_page)

    ## Initializing the @offering object so that we can render the show partial
    @offering = @offerings.first unless @offering

    return true

  end

  def get_deity
    @deity = Deity.find(params[:deity_id]) if params[:deity_id]
  end

  def set_deity_and_temple
    if @deity && @offering
      @offering.deity = @deity
      @offering.temple = @deity.temple
    end
  end

  def offering_params
    params.require(:offering).permit(:name, :deity_id, :temple_id, :price, :devaswam_share, :shanti_share, :kazhakam_share, :notes)
  end

end

app/controllers/trust_admin/sessions_controller.rb
class TrustAdmin::SessionsController < TrustAdmin::BaseController

  skip_before_filter :require_trust_admin, :except => :sign_out
  before_filter :redirect_if_signed_in, :only => :sign_in

  def sign_in

  end

  ## This method will accept a proc, execute it and render the json
  def create_session

    # Fetching the user data (email / username is case insensitive.)
    @authenticated, @trust_admin, @heading, @alert = TrustAdmin.authenticate(params[:login_handle], params[:password])

    if @authenticated
      store_flash_message("#{@heading}: #{@alert}", :success)
      session[:trust_admin_id] = @trust_admin.id
      redirect_to redirect_url_after_sign_in
    else
      store_flash_message("#{@heading}: #{@alert}", :error)
      redirect_to redirect_url_if_sign_in_fails
    end

  end

  def sign_out

    @heading = translate("authentication.success")
    @alert = translate("authentication.logged_out_successfully")
    store_flash_message("#{@heading}: #{@alert}", :notice)

    # Reseting the auth token for user when he logs out.
    @current_trust_admin.update_attribute :auth_token, SecureRandom.hex

    session.delete(:trust_admin_id)

    redirect_to redirect_url_after_sign_out

  end

end

app/views/trust_admin/offerings/_field.html.erb
<%
  unless defined?(required)
    required = false
  end
  unless defined?(place_holder)
    place_holder = ""
  end
  inp_id = "inp_#{display_name.underscore.split(" ").join("_")}"
  error_class = object.errors[field_name.to_s].any? ? "has-error" : ""
%>

<div class="form-group <%= error_class %>">

  <% if ["text", "email", "search", "password", "date", "time", "tel", "url", "month", "file", "image", ""].include?(input_type) %>

    <label for="inp_<%= display_name.underscore.split(" ").join("_") %>" class="col-md-4 control-label">
      <%= display_name %>
      <span class="text-color-red ml-10 mr--5 pull-right"><%= required ? "*" : raw("&nbsp;&nbsp;") %></span>
    </label>
    <div class="col-md-8">
      <input name="<%= object_name %>[<%= field_name %>]" id="inp_<%= display_name.underscore.split(" ").join("_") %>" class="text input form-control" type="<%= input_type %>" placeholder="<%= place_holder %>" value="<%= object.send(field_name.to_s) %>" />
    </div>

  <% elsif input_type == "checkbox" %>

    <label for="inp_<%= display_name.underscore.split(" ").join("_") %>" class="col-md-4 control-label">
      <%= display_name %>
      <span class="text-color-red ml-10 mr--5 pull-right"><%= required ? "*" : raw("&nbsp;&nbsp;") %></span>
    </label>
    <div class="col-md-8">
      <input name="<%= object_name %>[<%= field_name %>]" id="inp_<%= display_name.underscore.split(" ").join("_") %>" type="<%= input_type %>" class="checkbox input form-control" <%= object.send(field_name.to_s) ? "checked='checked'" : "" %> />
    </div>

  <% elsif input_type == "textarea" %>

    <label for="inp_<%= display_name.underscore.split(" ").join("_") %>" class="col-md-4 control-label">
      <%= display_name %>
      <span class="text-color-red ml-10 mr--5 pull-right"><%= required ? "*" : raw("&nbsp;&nbsp;") %></span>
    </label>
    <div class="col-md-8">
      <textarea name="<%= object_name %>[<%= field_name %>]" style="height:200px;" class="textarea input form-control" id="inp_<%= display_name.underscore.split(" ").join("_") %> placeholder="<%= place_holder %>" "><%= object.send(field_name.to_s) %></textarea>
    </div>

  <% end %>

</div>

app/views/trust_admin/offerings/_filters.html.erb
<div class="row">
  <div class="col-xs-4">
    <%= link_to raw("<i class='icon-plus icon-white mr--5'></i> New Offering"), new_trust_admin_offering_path(deity_id: @deity.id), :class=>"btn btn-lg btn-warning", :remote=>true %>
  </div><!-- /.col-xs-6 -->

  <div class="col-xs-8">

    <%= form_for Offering.new, :url => trust_admin_offerings_path(deity_id: @deity.id), :method => :get, :remote=>true, :html=>{:class=>"pull-right", :style=>"m-bottom:0px;"} do |f| %>

    <div class="input-group">
      <input type="text" name="query" placeholder="Search Offerings ..." class="form-control">
      <span class="input-group-btn">
        <button type="submit" class="btn btn-default">Search!</button>
      </span>
    </div><!-- /input-group -->

    <%- end %>

  </div><!-- /.col-xs-6 -->
</div><!-- /.row -->

app/views/trust_admin/offerings/_form.html.erb
<%# Renders a partial which is used to create a new offering %>

<%= form_for([:trust_admin, @offering], :html => {:id=>"form_offering", :class=>"mb-0 form-horizontal", :role => "form", :method => (@offering.new_record? ? :post : :put), :remote=>true}) do |f| %>

  <div class="modal-body">

    <%= @offering.errors[:base].to_sentence %>

    <%= hidden_field_tag :faction, @offering.new_record? ? trust_admin_offerings_path : trust_admin_offerings_path(@offering) %>
    <%= hidden_field_tag :fmethod, @offering.new_record? ? "POST" : "PUT" %>

    <div class="form-inputs">

      @deity = <%= @deity.id %>

      <!-- Name (string) -->
      <%= render :partial=>"field", :locals=>{:object=>@offering,
                                              :object_name=>'offering',
                                              :field_name=>'name',
                                              :display_name=>'Name',
                                              :field_type=>'string',
                                              :input_type=>'text',
                                              :required=>true,
                                              :place_holder=>"e.g: Put a suitable example here."} %>

      <!-- Temple (integer) -->
      <% if @deity && @deity.id %>
        <div class="form-inputs">

          <div class="form-group ">
            <label for="inp_temple" class="col-md-4 control-label">Temple
              <span class="text-color-red ml-10 pull-right">*</span>
            </label>
            <div class="col-md-8">
              <%= @deity.temple.name %>
            </div>
          </div>
        </div><!-- /.form-inputs -->

        <div class="form-inputs">
          <div class="form-group ">
            <label for="inp_temple" class="col-md-4 control-label">Deity
              <span class="text-color-red ml-10 pull-right">*</span>
            </label>
            <div class="col-md-8">
              <%= @deity.name %>
            </div>
          </div>
        </div><!-- /.form-inputs -->

        <%= hidden_field_tag "deity_id", @deity.id %>

      <% end %>

      <!-- Price (float) -->
      <%= render :partial=>"field", :locals=>{:object=>@offering,
                                              :object_name=>'offering',
                                              :field_name=>'price',
                                              :display_name=>'Price (in Rs)',
                                              :field_type=>'float',
                                              :input_type=>'text',
                                              :required=>true,
                                              :place_holder=>"e.g: 25."} %>
      <!-- Devaswam Share (float) -->
      <%= render :partial=>"field", :locals=>{:object=>@offering,
                                              :object_name=>'offering',
                                              :field_name=>'devaswam_share',
                                              :display_name=>'Devaswam Share (in Rs)',
                                              :field_type=>'float',
                                              :input_type=>'text',
                                              :required=>true,
                                              :place_holder=>"e.g: 10."} %>
      <!-- Shanti Share (float) -->
      <%= render :partial=>"field", :locals=>{:object=>@offering,
                                              :object_name=>'offering',
                                              :field_name=>'shanti_share',
                                              :display_name=>'Shanti Share (in Rs)',
                                              :field_type=>'float',
                                              :input_type=>'text',
                                              :required=>true,
                                              :place_holder=>"e.g: 10."} %>
      <!-- Kazhakam Share (float) -->
      <%= render :partial=>"field", :locals=>{:object=>@offering,
                                              :object_name=>'offering',
                                              :field_name=>'kazhakam_share',
                                              :display_name=>'Kazhakam Share (in Rs)',
                                              :field_type=>'float',
                                              :input_type=>'text',
                                              :required=>true,
                                              :place_holder=>"e.g: 5."} %>

      <!-- Notes (string) -->
      <%= render :partial=>"field", :locals=>{:object=>@offering,
                                              :object_name=>'offering',
                                              :field_name=>'notes',
                                              :display_name=>'Notes',
                                              :field_type=>'string',
                                              :input_type=>'text',
                                              :required=>false,
                                              :place_holder=>"e.g: Put a suitable example here."} %>

    </div>

  </div>

  <div class="modal-footer">

    <div class="pull-right">
      <% button_text = "#{@offering.new_record? ? "Create" : "Update"} Item" %>
			<%# if @offering.new_record? %>
				<%#= link_to "Cancel", "#", :class => "btn", :remote=>true %>
			<%# else %>
				<%#= link_to 'Back', trust_admin_offerings_path, :class=>"btn ml-10", :remote => true unless @offering.new_record? %>
			<%# end %>
      <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      <%= submit_tag button_text, "data-reset-text"=>button_text, "data-loading-text"=>"Saving ...", :class=>"btn btn-primary ml-10" %>
    </div>

  </div>

	<div class="cl-10"></div>

<% end %>

app/views/trust_admin/offerings/_index.html.erb
<%# Displays list of @offerings %>
<table id="table_offering_collections" class="table table-striped table-hover">
  <tr>
    <th style="width:20%;text-align:left;">Name</th>
    <th style="width:8%;text-align:left;">Price</th>
    <th style="width:8%;text-align:left;">Devaswam</th>
    <th style="width:8%;text-align:left;">Shanti</th>
    <th style="width:8%;text-align:left;">Kazhakam</th>
    <th style="text-align:center;">Notes</th>
    <th style="width:20%;text-align:center;">Action</th>
  </tr>
  <% @offerings.each do |offering| %>
    <tr id="tr_offering_<%= offering.id %>">
      <%= render :partial=>"item", :locals=>{:offering=>offering} %>
    </tr>
  <% end %>
  <% if @offerings.blank? %>
    <tr id="tr_offering_empty" class="text-color-grey p-80 text-align-center">
      <td colspan="4"><%= translate("forms.no_results_found") %></td>
    </tr>
  <% end %>
</table>

<% if @offerings.any? %>
   <%= content_tag :div, :class=>"pull-right" do %>
     <%= paginate @offerings, :remote => true %>
   <% end %>
<% end %>
<div class="cl"></div>

app/views/trust_admin/offerings/_item.html.erb
<%# describes about each offering %>
<td><%= offering.name %></td>
<td><%= offering.price %></td>
<td><%= offering.devaswam_share %></td>
<td><%= offering.shanti_share %></td>
<td><%= offering.kazhakam_share %></td>
<td><%= scrap_word(offering.notes, 160) %></td>
<td>
  <%= link_to raw("<i class=\"icon-remove \"></i> Delete"), trust_admin_offering_path(offering), method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-sm pull-right", :remote=>true %>
  <%= link_to raw("<i class=\"icon-pencil icon-white mr-5\"></i> Edit"), edit_trust_admin_offering_path(offering), :class=>"btn btn-default btn-sm pull-right mr-10", :remote=>true %>
</td>

app/views/trust_admin/offerings/_new.html.erb
<%# Used to create a new Offering %>
<div class="box p-10">
  <div class="p-10 text-color-blue fs-18 mb-20">
    Create a New Offering
  </div>
	<%= render 'form' %>
</div>

app/views/trust_admin/offerings/_show.html.erb
<%# Displays a detailed view of the offering %>
<%# Display Flash Message if any only in case of ajax request %>
<% if request.xhr? %>
	<%= render :partial=>"layouts/common/flash_message" %>
<% end %>

<div class="box p-10">

  <div class="row">
    <div class="col-md-3">
      <%= display_image(@offering, :photo, "100%") %>
    </div>

    <div class="col-md-9">
      <div class="heading1">This is a heading <%#= @offering.id %></div>
      <div class="heading2">Sub heading <%#= @offering.another_field %></div>
    </div>
  </div>

  <table class="table table-condensed table-hover table-striped mt-20">
    <tbody>
      <tr>
        <td class="bold" style="width:30%;">Id</td>
        <td><%= @offering.id %></td>
      </tr>
      <tr>
        <td class="bold" style="width:30%;">Created at</td>
        <td><%= display_time(@offering.created_at, "text-color-grey") %></td>
      </tr>
      <tr>
        <td class="bold" style="width:30%;">Last updated at</td>
        <td><%= display_time(@offering.updated_at, "text-color-grey") %></td>
      </tr>
    </tbody>
  </table>

	<div class="row">
    <%= content_tag :span, "Notes:", :style=>"font-weight:bold", :class=>"col-md-4" %>
    <%= content_tag :span, @offering.notes, :class=>"col-md-8 ext-color-grey" %>
	</div>

  	<div class="row">
      <%= content_tag :span, "Deity:", :style=>"font-weight:bold", :class=>"col-md-4" %>
      <%= content_tag :span, @offering.deity_id, :class=>"col-md-8 ext-color-grey" %>
  	</div>
  	<div class="row">
      <%= content_tag :span, "Temple:", :style=>"font-weight:bold", :class=>"col-md-4" %>
      <%= content_tag :span, @offering.temple_id, :class=>"col-md-8 ext-color-grey" %>
  	</div>
  	<div class="row">
      <%= content_tag :span, "Price:", :style=>"font-weight:bold", :class=>"col-md-4" %>
      <%= content_tag :span, @offering.price, :class=>"col-md-8 ext-color-grey" %>
  	</div>


  <div class="cl-20"></div>

  <div class="palette-footer ml-10">
    <%= link_to raw("<i class=\"icon-pencil icon-white mr--5\"></i> Edit"), edit_trust_admin_offering_path(@offering), :class=>"btn btn-default btn-sm pull-right ml-10", :remote=>true %>
    <%= link_to raw("<i class=\"icon-remove \"></i> Delete"), trust_admin_offering_path(@offering), method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-sm pull-right", :remote=>true %>
    <div class="cl-10"></div>
  </div>

</div>

app/views/trust_admin/offerings/_summary.html.erb
<%# Displays Total number of items in the system %>
<%# Display Flash Message if any only in case of ajax request %>
<% if request.xhr? %>
	<%= render :partial=>"layouts/common/flash_message" %>
<% end %>

<div class="box text-color-grey p-80 text-align-center" style="height:200px;">
  Total Offerings = <%= Offering.count %>
</div>